CREATE TABLE IF NOT EXISTS test.koi8r
  ( id INTEGER UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT
  , doc TEXT
  ) DEFAULT CHARACTER SET = koi8r DEFAULT COLLATE = koi8r_general_ci;

INSERT INTO test.koi8r VALUES ('abc def кгб');
